version: '2'
services:
    crrsvc-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/crrsvc/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=crrsvc
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
